name: department_and_product
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  hooks_riverpod: 2.5.1
  flutter_hooks: 0.20.5
  dio: 5.4.3+1
  freezed: 2.5.2
  freezed_annotation: 2.4.1
  envied: 0.5.4+1
  cached_network_image: 3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 3.0.2
  envied_generator: 0.5.4+1
  build_runner: 2.4.9
  json_serializable: 6.8.0
  

flutter:
  uses-material-design: true